### ISSUE TITLE
[BUG] - Inventory Embed Limits

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/christmas-bot#30]
# Bug Report

## Describe the bug

Discord has a strict limit on embed descriptions of 2048 characters. It's very likely that, as user inventories grow, we will hit that limit.

## Expected behavior

Either we can paginate the embeds using reactions, or split the embeds into multiple.

**Comment by rgroves** [comment]
I can pick this up and work on it, assuming you either don't want to do the inventory breakout as mentioned in #23 or that maybe that will be a future addition and for now I can use the character data to figure out item categorization so that the inventory list can be broken out and paginated by common/uncommon/rare groupings.
