### ISSUE TITLE
[FEAT] - Add additional characters

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/christmas-bot#5]
# Feature Request

## Is your feature request related to a problem? Please describe:

The goal is to have 50 different characters in the `src/data/characters.ts` array.

## Describe the solution you'd like

This issue can be handled all at once, or characters can be PRed in as contributors think of them.

**Comment by rgroves** [comment]
I'll work on adding some characters, but have a couple of questions:

1. Are there any guidelines to follow for adding characters (are any Christmas related characters allowed? Should we stick to non-copyrighted characters who must be in the public domain? etc.)
2. Is it okay to add characters but not complete the items and just leave some as "TODO" to flag them as some ideas are needed for items for those characters?

**Comment by nhcarrigan** [comment]
I think they should all be Christmas characters, really - since this will be proposed for a Christmas event. 🤔 We should stick to public domain characters, or generic characters that don't infringe on copyrights for sure. 

And absolutely! You'll get errors if you leave the properties missing, but you can add the properties with a value of `"TODO"`.

**Comment by rgroves** [comment]
I have brainstormed an initial set of 20 characters and corresponding items (60 items in total). 

Some of these might not make the cut, but I assume they can be edited/removed as we go if there are better options or some of this are deemed unfit.

I grammatically styled the character names and item descriptions so that they would fit "Mad Libs" style into the types of message formats shown below. Depending on the direction that the final messages used take, these names/descriptions may need to be tweaked.

- Appearance Message: "_[**character-name**]_ has appeared. Reward them with _[naughty|nice]_."
- Reward Message: "They give _[user-name]_ _[**item-description**]_."

I have also put together [this google sheet with this info as well](https://docs.google.com/spreadsheets/d/1-cb6BEsVcX3_U5L5yxX2hWIZ4ju0E78ysmEirhv-A1U/edit#gid=0). It is currently editable by anyone. I figure we can use this to ask for input from those in the fCC Discord server who might have ideas, but might not necessarily want to contribute via GitHub. It's also easy to take this and generate the JS needed to pop into the `src/data/characters.ts` file. If you want to use this, feel free to either make a copy of your own or use this as the official list.

Coming up with public domain characters was kind of hard for me. My initial brainstorm had an additional 10 but those were characters under copyright. In some cases, I just genericized the name and let the item description do the work in filling out who it refers to, examples:

- **Santa's 9th Reindeer**:
  - _some reindeer lichen_
  - _an official Reindeer Games Rulebook_
  - _a flashing red LED_
- **A Hard-Boiled NYPD Cop**:
  - _a Christmas party invitation_
  - _a classic one-liner_
  - _a bag of detonators_

The first above is a nod to Rudolph, while not actually saying Rudolph.
The second above is a nod to John McClane... (which, being a reference from the classic 1988 Christmas movie Die Hard, I know might not make the final cut—but it's a good example in terms of how to try and genericize something not in public domain).

PR inbound for review.

**Comment by nhcarrigan** [comment]
Closing as project is being tabled.
